Add support to upload an user avatar/profile image
antoniomnds/ebook_store pull request #10
Opened 2024-09-20 10:42 UTC by antoniomnds

2024-09-20 11:33 UTC, luispcosta requested changes

2024-09-20 11:33 UTC, luispcosta commented on app/views/users/_user.html.erb
> +        <%= image_tag user.avatar.variant(resize_to_limit: [250, 250]) %>
Mete esta lógica num método que te retorne a image tag do avatar. Meter lógica de negócio numa view geralmente não é boa ideia

2024-09-20 11:33 UTC, luispcosta commented on config/sidekiq.yml
> +:max_retries: 5
Esta syntax não me parece correta, acho que tens um `:` a mais no inicio

2024-09-20 14:42 UTC, antoniomnds commented on config/sidekiq.yml
> +:max_retries: 5
Foi a minha ideia inicial mas depois vi nos [docs](https://github.com/sidekiq/sidekiq/wiki/Error-Handling#automatic-job-retry) e tudo o que leva um valor tem essa sintaxe.

2024-09-27 09:43 UTC, firedeathz approved these changes

2024-09-30 09:09 UTC, luispcosta approved these changes

2024-10-01 15:16 UTC, merged