Add admin user
antoniomnds/ebook_store pull request #16
Opened 2024-09-24 17:33 UTC by antoniomnds

2024-09-25 08:57 UTC, luispcosta requested changes

2024-09-25 08:57 UTC, luispcosta commented on config/routes.rb
> +  end if Rails.env.production?
Meteste-te o sidekiq mas não estou a ver o sidekiq a ser usado neste PR, é para ser usado no futuro?

2024-09-25 12:43 UTC, antoniomnds commented on config/routes.rb
> +  end if Rails.env.production?
Realmente não é usado neste PR. Fiquei de adicionar o monitor, achando que poderia tirar partido da implementação do user admin, ou seja, apenas estar acessível a utilizadores admin. Acabei por adicionar uma autenticação standard conforme documentado por achar que seria mais seguro.

2024-10-01 14:59 UTC, firedeathz approved these changes

2024-10-01 14:59 UTC, firedeathz commented on app/controllers/users_controller.rb
> +                status: :see_other unless @user == current_user || current_user.is_admin?
esta sintaxe até pode funcionar assim, mas este é um dos casos em que eu prefiro ou meter o `unless` fora, tipo assim:
```rb
unless @user == current_user
  redirect_to ...
end
```
ou usar parentesis à volta dos params do `redirect_to`, para ser mais fácil de perceber se o unless aplica-se ao método todo ou só ao status

2024-10-01 15:03 UTC, antoniomnds commented on app/controllers/users_controller.rb
> +                status: :see_other unless @user == current_user || current_user.is_admin?
Sim, de facto está pouco legível. Irei alterar para um bloco `unless` :)

2024-10-01 16:39 UTC, merged