Fetch ebook summary from API
antoniomnds/ebook_store pull request #21
Opened 2024-10-03 08:22 UTC by antoniomnds

2024-10-03 10:22 UTC, firedeathz commented on app/views/ebooks/_ebook.html.erb
> +            Load Summary from New York Times
porque não ir buscar o summary a nivel do `#show` no controlador e evitar esta "treta" de ter um botão e um controller JS para te fazer o pedido async?
Por um lado é fixe teres ficado a perceber como usar os controllers JS para fazer isto, mas parece-me um bocado overkill aqui :D

2024-10-03 10:31 UTC, antoniomnds commented on app/views/ebooks/_ebook.html.erb
> +            Load Summary from New York Times
Verdade. Estava fixado em obter os dados em consequência de uma interação do utilizador e nem me lembrei dessa abordagem. Evitava ter perdido tempo a "batalhar" com o JS. Bem, fico com um caso de uso.

Nesse caso, atribuía o summary a uma variável no controlador e passava-a ao template?

2024-10-03 10:35 UTC, firedeathz commented on app/views/ebooks/_ebook.html.erb
> +            Load Summary from New York Times
> Nesse caso, atribuía o summary a uma variável no controlador e passava-a ao template?
Sim, parece-me bem 👍

2024-10-03 11:39 UTC, antoniomnds commented on app/views/ebooks/_ebook.html.erb
> +            Load Summary from New York Times
Feito ✔️

2024-10-04 08:28 UTC, luispcosta requested changes

2024-10-04 08:28 UTC, luispcosta commented on app/controllers/ebooks_controller.rb
> +    @review = Ebook::MetadataService.get_review(@ebook)
Se o serviço der um erro a buscar as reviews, o teu método retorna `nil`. Penso que não estejas a lidar com isso. Ou vais fazer isso depois num PR futuro?

2024-10-04 09:27 UTC, antoniomnds commented on app/controllers/ebooks_controller.rb
> +    @review = Ebook::MetadataService.get_review(@ebook)
Acabei por lidar com isso no `ebook_helper`:
`return unless review&.any? && review.first["summary"]&.present?`

Talvez não seja o sítio mais indicado?

2024-10-04 10:20 UTC, luispcosta commented on app/controllers/ebooks_controller.rb
> +    @review = Ebook::MetadataService.get_review(@ebook)
Não tinha visto. Parece-me ok então

2024-10-04 10:20 UTC, luispcosta approved these changes

2024-10-19 14:54 UTC, merged